# Site settings
title: Ameba Stack
email: intelligentcodemail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/Ameba
  - title: google-plus
    url: https://plus.google.com/116577209082774853202/posts
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/amebastack

# Build settings
markdown: kramdown
permalink: pretty
