# Site settings
title: Ameba Stack
email: intelligentcodemail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6db33f
  secondary: 34302d
  secondary-dark: 262626

social:
  - title: github
    url: http://github.com/Ameba
  - title: bug
    url: https://github.com/Ameba/AmebaStack/issues
  - title: google-plus
    url: https://plus.google.com/116577209082774853202/posts
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/amebastack
  - title: envelope-o
    url: mailto:intelligentcodemail@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
